services:
  publisher:
    build: ./publisher
    depends_on:
      - redis
  subscriber:
    build: ./subscriber
    depends_on:
      - redis
    deploy:
      replicas: 2
  redis:
    image: redis
